# Generated by Django 4.2.7 on 2024-10-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tren', models.CharField(default='Tren', max_length=4, verbose_name='tren')),
                ('vagon', models.CharField(default='1', max_length=4, verbose_name='Vagon')),
                ('asiento', models.CharField(default='1', max_length=10, verbose_name='Asiento')),
            ],
        ),
    ]
