# Generated by Django 4.2.7 on 2024-10-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0002_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='asiento',
            field=models.CharField(default='1', max_length=3, verbose_name='asiento'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=30, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='folio',
            field=models.CharField(default='0000', max_length=10, verbose_name='folio'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='nota',
            field=models.CharField(default='None', max_length=150, verbose_name='notas'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='observaciones',
            field=models.CharField(default='None', max_length=150, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='precio',
            field=models.CharField(default='0.00', max_length=10, verbose_name='asiento'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='tren',
            field=models.CharField(default='1', max_length=3, verbose_name='Tren'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='vagon',
            field=models.CharField(default='1', max_length=3, verbose_name='Vagon'),
        ),
    ]
