# Generated by Django 4.2.7 on 2024-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0003_boleto_asiento_boleto_estatus_boleto_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='num_personas',
            field=models.IntegerField(default=1, max_length=3, verbose_name='Num Personas'),
        ),
    ]
